
name: My First Workflow

on: [push]                              # Trigger on Push Event

jobs:  
  job-single-command:                                # build job
    runs-on: ubuntu-latest              # runner

    steps:                              # git checkout step
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Hello universe                 # running a single command
      run: echo "Hello, World!"

  job-smultiple-command:                                # build job
    runs-on: ubuntu-latest  
    needs: ["job-single-command"]            # runner

    steps:                              # git checkout step
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Hello multiverse                 # running a single command
      run: |
        echo "fist of multicommands"
        echo "second of multicommands"