
name: My First Workflow

on: [push]                              # Trigger on Push Event

jobs:  
  build:                                # build job
    runs-on: ubuntu-latest              # runner

    steps:                              # git checkout step
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Hello World                 # running a single command
      run: echo "Hello, World!"