name: Workflow with manual trigger and Environment Variables

on:
  workflow_dispatch: # Manual trigger
# env:
#   WORKFLOW_ENV_VARIABLE: "Workflow Level"
env:
  MY_NAME: "akhilesh-mishra"

jobs:
  example_job:
    runs-on: ubuntu-latest
    env:
      JOB_ENV_VARIABLE: "Job Level"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Print Environment Variables
      run: |
        echo "Workflow Level Environment Variable: $WORKFLOW_ENV_VARIABLE"
        echo "Job Level Environment Variable: $JOB_ENV_VARIABLE"
        echo "Step Level Environment Variable: ${{ env.STEP_ENV_VARIABLE }}"
      env:
        STEP_ENV_VARIABLE: "Step Level"
  # new_job:
  #   runs-on: ubuntu-latest
  #   steps:

  #     - name: run a commands
  #       run: |
  #         echo ${{ emv.JOB_ENV_VARIABLE  }}
  #         echo ${{ emv.MY_NAME  }}
